ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from cart import views

from django.conf.urls.static import static
from django.conf import settings

app_name='cart'

urlpatterns = [
    path('addtocart/<int:i>',views.addtocart,name='addtocart'),
    path('cart',views.cart_view,name='cartview'),
    path('cartremove/<int:i>',views.cart_remove,name='cartremove'),
   path('cartdelete/<int:i>',views.cart_delete,name='cartdelete'),
    path('order',views.order_form,name='orderform'),
    path('status/<u>',views.payment_status,name='status'),
    path('orderview',views.order_view,name='orderview'),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls')),
    path('search/',include('search.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views

from django.conf.urls.static import static
from django.conf import settings

app_name='search'

urlpatterns = [
    path('search',views.search_products,name='search')
]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path,include
from shop import views

from django.conf.urls.static import static
from django.conf import settings

app_name='shop'

urlpatterns = [
    path('',views.categories,name='categories'),
    path('products/<int:p>',views.products,name='products'),
    path('details/<int:p>',views.details,name='details'),
    path('register',views.register,name='register'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('addcat',views.add_categories,name='addcat'),
    path('addpro',views.add_products,name='addpro'),
    path('addstock/<int:p>', views.add_stock, name='addstock')

]

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from shop.models import Product
# Create your models here.

class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateTimeField(auto_now_add=True)

    def subtotal(self):
        return self.quantity*self.product.price

class Payment(models.Model):
    name=models.CharField(max_length=30)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=30,blank=True)
    razorpay_payment_id=models.CharField(max_length=30,blank=True)
    paid=models.BooleanField(default=False)

class Order_details(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.BigIntegerField()
    pin=models.IntegerField()

    order_id=models.CharField(max_length=30)
    ordered_date=models.DateTimeField(auto_now_add=True)

    payment_status=models.CharField(max_length=30,default="pending")
    delivery_status=models.CharField(max_length=30,default="pending")

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from cart.models import Cart,Payment,Order_details
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import login
import razorpay
from django.views.decorators.csrf import csrf_exempt
# Create your views here.

@login_required
def addtocart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(product=p,user=u)    #checks the product present in cart table for the particular user
        if(p.stock>0):
            c.quantity+=1                        #if present it will increment the quantity of that particular product
            c.save()
            p.stock-=1
            p.save()

    except:
        if (p.stock > 0):
            c=Cart.objects.create(product=p,user=u,quantity=1)
            c.save()
            p.stock -= 1
            p.save()
            
    return redirect('cart:cartview')

@login_required
def cart_view(request):
    u=request.user
    #if particular product for a particular user already exists
    c=Cart.objects.filter(user=u)
    total=0

    for i in c:
        total+=i.quantity*i.product.price


    context={'cart':c,'total':total}

    return render(request,'cart.html',context)

@login_required
def cart_remove(request,i):
    p=Product.objects.get(id=i)
    u=request.user

    try:
        c=Cart.objects.get(product=p,user=u)
        if(c.quantity > 1):
            c.quantity-=1
            c.save()
            p.stock+=1
            p.save()

        else:
            c.delete()
            p.stock+=1
            p.save()

    except:
        pass
    return redirect('cart:cartview')


@login_required
def cart_delete(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    c=Cart.objects.get(product=p,user=u)
    c.delete()
    p.stock+=c.quantity
    p.save()

    return redirect('cart:cartview')

@login_required
def order_form(request):
    if(request.method=='POST'):
        a=request.POST['a']
        ph=request.POST['ph']
        pi=request.POST['pi']
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.quantity*i.product.price
        total1=int(total*100)
        # print(total)

        client=razorpay.Client(auth=('rzp_test_RbrhgeNE0WBB2W','mYhbXbCmP3ueeoIp0uCLIomZ'))  #creates a client connection using razorpay id and secret code.

        response_payment=client.order.create(dict(amount=total1,currency="INR"))    #creates an order with razorpay using razorpay client.

        # print(response_payment)

        order_id=response_payment['id']   #retrives the order id from response
        status=response_payment['status']   #retrives the status from response

        if(status=='created'):    #if status is created the store order_id in the Payment and Order_details Table.
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c:     #for each item creates a record inside Order_details table
                o=Order_details.objects.create(product=i.product,user=u,no_of_items=i.quantity,address=a,phone=ph,pin=pi,order_id=order_id)
                o.save()

        response_payment['name']=u.username
        context={'payment':response_payment}

        return render(request,'payment.html',context)

    return render(request,'order.html')


@csrf_exempt
def payment_status(request,u):
    usr = User.objects.get(username=u)
    if not request.user.is_authenticated:
        login(request,usr)
    # print(u)

    if(request.method=='POST'):
        response=request.POST
        print(response)

        param_dict={
            'razorpay_payment_id':response['razorpay_payment_id'],
            'razorpay_order_id':response['razorpay_order_id'],
            'razorpay_signature':response['razorpay_signature']
        }

        #To check the authenticity of the Razorpay Signature
        client = razorpay.Client(auth=('rzp_test_RbrhgeNE0WBB2W', 'mYhbXbCmP3ueeoIp0uCLIomZ'))
        # print(client)

        try:
            status=client.utility.verify_payment_signature(param_dict)
            print(status)

         #To retrive a particular record from Payment table matching with razorpay response order id
            p=Payment.objects.get(order_id=response['razorpay_order_id'])
            p. razorpay_payment_id=response['razorpay_payment_id']
            p.paid=True
            p.save()

         #To retrive the records from Order_details table matching with razorpay response order id
            o=Order_details.objects.filter(order_id=response['razorpay_order_id'])
            for i in o:
                i.payment_status='Paid'
                i.save()


                c=Cart.objects.filter(user=usr)  #filter all records matching with particular user
                c.delete()

        except:
            pass

    return render(request,'payment_status.html',{'status':status})

@login_required
def order_view(request):
    u=request.user
    o=Order_details.objects.filter(user=u)
    context={'order':o}
    return render(request,'orderview.html',context)

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
from django.contrib.auth.decorators import login_required
# Create your views here.

# @login_required
def search_products(request):
    # p=None
    # query=" "
    if(request.method=='POST'):
        query=request.POST['se']      #reads the query value
        print(query)
        if query:
            p=Product.objects.filter(Q(name__icontains=query))  #filter the records matching with the query
        context={'pro':p,'query':query}
    return render(request,'search.html',context)

ecommerce/templates/addcat.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center">Add Category Page</h3>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

<div class="container w-50">
  <div class="mb-3">
    <label class="form-label">Name</label>
    <input type="text" class="form-control" name="n" placeholder="Enter Category Name" >
  </div>

  <div class="mb-3">
  <label for="formFile" class="form-label">Image</label>
  <input class="form-control" type="file" name="i" id="formFile">
</div>

   <div class="mb-3">
    <label  class="form-label">Description</label>
        <textarea name="d" class="form-control" placeholder="Write Category Description"></textarea>
  </div>

  <button type="submit" class="btn btn-primary ">Submit</button>
</div>
</form>
{% endblock %}

ecommerce/templates/addpro.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center">Add Products Page</h3>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

<div class="container w-50">
  <div class="mb-3">
    <label class="form-label">Name</label>
    <input type="text" class="form-control" name="n" placeholder="Enter Product Name" >
  </div>

  <div class="mb-3">
  <label for="formFile" class="form-label">Image</label>
  <input class="form-control" type="file" name="i" id="formFile">
</div>

   <div class="mb-3">
    <label  class="form-label">Description</label>
        <textarea name="d" class="form-control" placeholder="Write Product Description"></textarea>
  </div>

    <div class="mb-3">
    <label class="form-label">Stock</label>
    <input type="number" class="form-control" name="s" placeholder="Enter Stock" >
  </div>

    <div class="mb-3">
    <label class="form-label">Price</label>
    <input type="number" class="form-control" name="p" placeholder="Enter Price" >
  </div>

    <div class="mb-3">
  <label>Category</label><br>
    <select name="c">
        {% for i in links %}
        <option value="{{i.name}}">{{i.name}}</option>
        {% endfor %}
    </select><br>
  <br>
    </div>

  <button type="submit" class="btn btn-primary ">Submit</button>
</div>
</form>
{% endblock %}

ecommerce/templates/addstock.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center">Add Stock Page</h3>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

<div class="container w-50">
  <div class="mb-3">
    <label class="form-label">Add Stock</label>
    <input type="number" class="form-control" name="s" value="{{pro.stock}}">
  </div>

    <button type="submit" class="btn btn-primary ">Submit</button>
</div>
</form>

{% endblock %}

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Offcanvas Menu Begin -->
    <div class="offcanvas-menu-overlay"></div>
    <div class="offcanvas-menu-wrapper">
        <div class="offcanvas__option">
<!--            <div class="offcanvas__links">-->
<!--                <a href="#">Sign in</a>-->
<!--                <a href="#">FAQs</a>-->
<!--            </div>-->
<!--            <div class="offcanvas__top__hover">-->
<!--                <span>Usd <i class="arrow_carrot-down"></i></span>-->
<!--                <ul>-->
<!--                    <li>USD</li>-->
<!--                    <li>EUR</li>-->
<!--                    <li>USD</li>-->
<!--                </ul>-->
<!--            </div>-->
        </div>
        <div class="offcanvas__nav__option">
            <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
            <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
            <div class="price">$0.00</div>
        </div>
        <div id="mobile-menu-wrap"></div>
        <div class="offcanvas__text">
            <p>Free shipping, 30-day return or refund guarantee.</p>
        </div>
    </div>
    <!-- Offcanvas Menu End -->

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-7">
                        <div class="header__top__left">
                            <p>Free shipping, 30-day return or refund guarantee.</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-5">
                        <div class="header__top__right">
<!--                            <div class="header__top__links">-->
<!--                                <a href="#">Sign in</a>-->
<!--                                <a href="#">FAQs</a>-->
<!--                            </div>-->
<!--                            <div class="header__top__hover">-->
<!--                                <span>Usd <i class="arrow_carrot-down"></i></span>-->
<!--                                <ul>-->
<!--                                    <li>USD</li>-->
<!--                                    <li>EUR</li>-->
<!--                                    <li>USD</li>-->
<!--                                </ul>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-3">
                    <div class="header__logo">
                        <a href="./index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <nav class="header__menu mobile-menu">
                        <ul>

                            <li><a href="{% url 'shop:categories' %}">Home</a></li>

                             <li><a href="#">All Categories</a>
                                <ul class="dropdown">

                                    {% for i in links %}
                                    <li><a href="{% url 'shop:products' i.id %}">{{i.name}}</a></li>
                                    {% endfor %}
                                    </ul>
                                 </li>

                            {% if user.is_authenticated %}
                            {% if user.is_superuser == False %}      <!-- normal user -->

                             <li><a href="{% url 'cart:orderview' %}">View Orders</a></li>
                             <a href="{% url 'cart:cartview' %}"><img src="{% static 'img/icon/cart.png' %}" alt=""><sup class="mx-2 fs-5 text-dark">{{count}}</sup></a>

                            {% else %}
                            <li><a href="{% url 'shop:addcat' %}">Add Categories</a></li>
                            <li><a href="{% url 'shop:addpro' %}">Add Products</a></li>

                            {% endif %}
                             <li><a href="{% url 'shop:logout' %}">Logout</a></li>

                            {% else %}
                            <li><a href="{% url 'shop:register' %}">Register</a></li>
                            <li><a href="{% url 'shop:login' %}">Login</a></li>
                            {% endif %}

                        </ul>

                    </nav>
                </div>
                <div class="col-lg-3 col-md-3">
                    <div class="header__nav__option">

                        <form class="d-flex" method="POST" action="{% url 'search:search' %}">
                            {% csrf_token %}
    <input class="mb-3 mx-3 me-2  border border-dark" type="search" name="se" placeholder="Search" aria-label="Search" >
    <button class=" mb-3 btn btn-outline-dark" type="submit">Search</button>
                        </form>

<!--                        <a href="{% url 'search:search' %}" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>-->
<!--                        <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>-->
<!--                        <div class="price">$0.00</div>-->
                    </div>
                </div>
            </div>
            <div class="canvas__open"><i class="fa fa-bars"></i></div>
        </div>
    </header>
    <!-- Header Section End -->


{% block content %}
{% endblock %}

 <!-- Footer Section Begin -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a>
                        </div>
                        <p>The customer is at the heart of our unique business model, which includes design.</p>
                        <a href="#"><img src="{% static 'img/payment.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="#">Clothing Store</a></li>
                            <li><a href="#">Trending Shoes</a></li>
                            <li><a href="#">Accessories</a></li>
                            <li><a href="#">Sale</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Payment Methods</a></li>
                            <li><a href="#">Delivery</a></li>
                            <li><a href="#">Return & Exchanges</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                    <div class="footer__widget">
                        <h6>NewLetter</h6>
                        <div class="footer__newslatter">
                            <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                            <form action="#">
                                <input type="text" placeholder="Your email">
                                <button type="submit"><span class="icon_mail_alt"></span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="footer__copyright__text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <p>Copyright ©
                            <script>
                                document.write(new Date().getFullYear());
                            </script>2020
                            All rights reserved | This template is made with <i class="fa fa-heart-o"
                            aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        </p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search Begin -->
    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form">
                <input type="text" id="search-input" placeholder="Search here.....">
            </form>
        </div>
    </div>
    <!-- Search End -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

ecommerce/templates/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2 class="text-center">Cart Page</h2>

<div class="container mt-5 p-3" style="margin-bottom:100px;">
      <h3 class="text-center">Shopping Cart</h3>
<div class="row">


    <div class="col-7">
<table class="table table-bordered border-2 border-danger text-center mt-3">
    <tr>
        <th colspan="5" class="text-center">Cart Items</th>
    </tr>

    {% for i in cart %}

    <tr>
        <td class="p-3"><img src="{{i.product.image.url}}" height="150px"></td>
        <td class="p-3">Product:{{i.product.name}}</td>
        <td class="p-3">Quantity:{{i.quantity}}<br>
        Unit Price:{{i.product.price}}</td>
        <td class="p-3">Subtotal:{{i.subtotal}}</td>

        <td>
            {% if i.product.stock > 0 %}
            <a href="{% url 'cart:addtocart' i.product.id %}"><i class="fa-solid fa-circle-plus text-dark"></i></a>
        <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa-solid fa-circle-minus text-dark"></i></a>
        <a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa-solid fa-trash text-dark"></i></a>
        {% else %}

        <a href="{% url 'cart:cartremove' i.product.id %}"><i class="fa-solid fa-circle-minus text-dark"></i></a>
        <a href="{% url 'cart:cartdelete' i.product.id %}"><i class="fa-solid fa-trash-can text-dark"></i></a></td>
        {% endif %}

    </tr>

    {% endfor %}

</table>
        </div>


             <div class="col-4 mt-3">
                 <table class="table table-bordered">
            <tr>
              <th colspan="4" class="text-center">Check Out</th>
            </tr>

            <tr>
              <td class="text-center">Total Price:{{total}}</td>
            </tr>
                 </table>


                <div class="d-flex justify-content-between">
                    <a href="{% url 'cart:orderform' %}" class="btn btn-secondary">Place Order</a>
                    <a href="" class="btn btn-secondary">Continue Shopping</a>
                </div>
             </div>

</div>
    </div>



{% endblock %}

ecommerce/templates/details.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="card mb-3 mt-3 mx-auto bg-secondary" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4 ">
      <img src="{{product.image.url}}" class="rounded-start" alt="..." height="200px" width="100%">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title text-warning"><u>{{product.name}}</u></h5>
        <p class="card-text">STOCK:{{product.stock}}</p>
        <p class="card-text">{{product.description}}</p>
        <p class="card-text">${{product.price}}</p>

        {% if request.user.is_superuser == True %}
          {% if product.stock > 0 %}
        <h5>Product In Stock</h5>
        <a href="{% url 'shop:addstock' product.id %}" class="btn btn-primary fw-bold mt-3 mb-2 text-center">ADD STOCK</a>
          {% else %}
        <h5>Product Out Of Stock</h5>
        <a href="{% url 'shop:addstock' product.id %}" class="btn btn-primary fw-bold mt-3 mb-2 text-center">ADD STOCK</a>
          {% endif %}

        {% else %}
        {% if product.stock > 0 %}
        <a href="{% url 'cart:addtocart' product.id %}" type="button" class="btn btn-primary mx-auto">Add to cart</a>
        {% else %}
        <h5>Out Of Stock</h5>
        {% endif %}

        {% endif %}
<!--        #this indicates the first if-->
      </div>
    </div>
  </div>
</div>

{% endblock %}

ecommerce/templates/products.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
<div class="bg-primary">
<img src="{{cat.image.url}}" class="rounded mx-auto d-block mt-3" alt="..." height="500px" width="100%">
<h2 class="text-center mt-3 ">{{cat.name}}</h2>
<h4 class="mt-4 text-center text-danger">{{cat.description}}</h4>
    </div>
<div class="container mt-3 p-3">

     <div class="row">
<div class="d-flex justify-content-between">
         {% for i in pro %}
                <div class="col-sm-4 py-4">
        <div class="card" style="width: 18rem;">

            <img src="{{i.image.url}}" class="card-img-top" alt="..." height="250px" width="100%">

            <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.price}}</p>

                <div class="d-flex justify-content-around">
                            <a href="{% url 'shop:details' i.id %}" type="button" class="btn btn-primary">Details</a>
                        </div>
                    </div>
                </div>
    </div>
    {% endfor %}
</div>
</div>
</div>

{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="text-center">Search Page</h3>

<!--{% if pro == None %}-->

<!--<form class="d-flex" method="POST">-->
<!--    {% csrf_token %}-->
<!--    <input class="mb-3 mx-5 me-2 mt-3 border border-dark" type="search" name="se" placeholder="Search" aria-label="Search" >-->
<!--    <button class=" mb-3 mt-3 btn btn-outline-dark" type="submit">Search</button>-->
<!--</form>-->

<!--{% else %}-->
<div class="container mt-3 p-3">
    <h3 class="text-center">You Have Searched For {{query}}</h3>
     <div class="row">
<!--<div class="d-flex justify-content-between">-->
         {% for i in pro %}
                <div class="col-sm-4 py-4">
        <div class="card" style="width: 18rem;">

            <img src="{{i.image.url}}" class="card-img-top" alt="..." height="250px" width="100%">

            <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.price}}</p>

                <div class="d-flex justify-content-around">
                            <a href="{% url 'shop:details' i.id %}" type="button" class="btn btn-primary">Details</a>
                        </div>
                    </div>
                </div>
                </div>

    {% empty %}
         <div>
    <h3 class="text-danger text-center">No Results Found</h3>
             </div>

    {% endfor %}
<!--    {% endif %}-->
</div>
</div>
{% endblock %}